NETWORKS_CODES = [
    "01",
    "02",
    "03",
    "04",
    "05",
    "06",
    "07",
    "08",
    "09",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20",
    "21",
    "22",
    "23",
    "24",
    "25",
    "26",
    "27",
    "28",
    "30",
    "31",
    "35",
    "88",
    "89",
    "90",
    "91",
    "93",
    "94",
    "95",
    "96",
    "97",
    "98",
]

NETWORKS_NAMES = [
    "Orange",
    "Orange",
    "MobiquiThings",
    "Sisteer",
    "Globalstar Europe",
    "Globalstar Europe",
    "Globalstar Europe",
    "SFR",
    "SFR",
    "SFR",
    "SFR",
    "Hewlett-Packard France",
    "SFR",
    "RFF",
    "Free mobile",
    "Free mobile",
    "Legos",
    "Voxbone",
    "Altitude infrastructure",
    "Bouygues Telecom",
    "Bouygues Telecom",
    "Transatel",
    "Omea Telecom",
    "MobiquiThings",
    "Lycamobile",
    "Bouygues Télécom Business distribution",
    "Coriolis Télécom",
    "AIF",
    "Symacom",
    "Mundio Mobile",
    "Free mobile",
    "Bouygues Telecom",
    "Fondation b-com",
    "Association Images & Réseaux",
    "Orange",
    "TDF",
    "Halys",
    "Orange",
    "Axione",
    "Thales communications",
    "Air France",
]


def convert_network_code_to_name(code: str) -> str:
    '''
    Convert networks codes to networks names.
    Use two list :
    - one for names
    - one for codes
    
    The indexes are the same so we can use index of codes to get corresponding name.
    '''
    return NETWORKS_NAMES[NETWORKS_CODES.index(code[-2:])]
